### ISSUE TITLE
--color Hex value support?

### ISSUE THREAD

**Issue by lovebdsobuj** [Pythonity/icon-font-to-png#3]
:+1: Very nice and most useful utility...
---
I try `--color` with hex value, but I got error, **icon-font-to-png** would support custom colorize by hex values.

**Comment by pawelad** [comment]
Hex values are supported:

```
$ font-awesome-to-png --color '#0f0f0f' star 
Exporting icon 'star' as 'star.png'(16x16 pixels)

All done
```

**Comment by lovebdsobuj** [comment]
Great!
It works for me...
I forgot to add `quote/''` symbol.

**Comment by lovebdsobuj** [comment]
Set this Post Label... That may help others user...

**Comment by pawelad** [comment]
I added an example with hex value to README.

**Comment by lovebdsobuj** [comment]
Okay...
