### ISSUE TITLE
How to know downloadable available fonts name?

### ISSUE THREAD

**Issue by lovebdsobuj** [Pythonity/icon-font-to-png#4]
Is there any command for listing, downloadable available fonts name.

**Comment by pawelad** [comment]
It's listed in `argparse` usage, so `-h`/`--help`:
```
usage: icon-font-to-png [-h] [--list] [--download {font-awesome,octicons}]
                        [--ttf TTF-FILE] [--css CSS-FILE] [--size SIZE]
                        [--scale SCALE] [--color COLOR] [--filename FILENAME]
                        [--keep_prefix]
                        [icons [icons ...]]

...

  --download {font-awesome,octicons}
                        download latest icon font and exit
```

**Comment by lovebdsobuj** [comment]
I'm talking about more fonts download way...?

**Comment by pawelad** [comment]
Only `Font Awesome` and `Octicons` are implemented at the moment. There could be more added in the future, but probably not any time soon.

But feel free to create a pull request with added icon font support.

**Comment by lovebdsobuj** [comment]
I have collections some of fonts, can I upload that all fonts into this project and update `icon_font_downloader.py`

**Comment by pawelad** [comment]
No CSS and TFF files are in the repository. To add support to new font you have to create new class that inherits from `IconFontDownloader` and add tests to make sure they're working properly. If you have experience with programming looking through `icon_font_downloader.py` and their respective tests should be enough.

**Comment by lovebdsobuj** [comment]
Okay, I'll try...
