### ISSUE TITLE
No such file or directory: 'icon-font-to-png/requirements.txt'

### ISSUE THREAD

**Issue by lovebdsobuj** [Pythonity/icon-font-to-png#5]
`$ pip install -r icon-font-to-png/requirements.txt`
> Could not open requirements file: [Errno 2] No such file or directory: `'icon-font-to-png/requirements.txt'
`

**Comment by pawelad** [comment]
You're probably executing the command from wrong directory - you should do `pip install -r requirements.txt` from repository root.
And you only need it if you cloned the repository and want to contribute or run it without installing it via `pip`. If you installed it via `pip install icon_font_to_png` you don't need to do anything else.

**Comment by lovebdsobuj** [comment]
So, update README.md file...
`Line 32: $ pip install -r icon-font-to-png/requirements.txt`
