### ISSUE TITLE
There is no ttf inside Octicons repository.

### ISSUE THREAD

**Issue by fragrans** [Pythonity/icon-font-to-png#8]
Hi,
How can I generate PNGs from Octicons, I didn't find any *.ttf inside the project. 

Thanks,
Fragrans

**Comment by pawelad** [comment]
You need to first download the CSS and TTF files va `icon-font-to-png --download octicons` command and then pass those files via `--css` and `--ttf` parameters, so:

```
$ icon-font-to-png --download octicons
$ icon-font-to-png --css octicons.css --tff octicons.ttf ALL
```

**Comment by fragrans** [comment]
It just works like charm.
Thanks,

BTW, there is no executable within windows release (pypi).
I have to run it with: 
`> python icon-to-fon-png ...`

And I created a very simple batch file to simplify the command line, attached as zip file.
[icon-font-to-png.zip](https://github.com/Pythonity/icon-font-to-png/files/672430/icon-font-to-png.zip)

**Comment by pawelad** [comment]
Glad I was able to help, and cool it's working on Windows - I never tested it there.
