### ISSUE TITLE
KeyError in PIL with Keyrune

### ISSUE THREAD

**Issue by MrGreenTea** [Pythonity/icon-font-to-png#9]
When I try to convert all Icons from https://github.com/andrewgioia/Keyrune I get a KeyError because it tries to convert an icon and save it as '.png' without prefix.
The list seems to contain an empty name as first element. I don't know anything about icon fonts, so I can't tell who is wrong here. Maybe allow the tool to ignore these errors and just tell the user that it couldn't convert it?
Thanks for the tool btw :)

**Comment by pawelad** [comment]
Could you paste the stacktrace here please? That should give me a bit more info about the problem and maybe provide a quick fix.

**Comment by MrGreenTea** [comment]
✘  (testing) /tmp  icon-font-to-png --css Keyrune-master/css/keyrune.css --ttf Keyrune-master/fonts/keyrune.ttf --size 64 ALL
    Exporting icon '' as '.png'(64x64 pixels)
    Traceback (most recent call last):
      File "/home/jonas/.virtualenvs/testing/bin/icon-font-to-png", line 16, in <module>
    command_line.run(sys.argv[1:])
      File "/home/jonas/.virtualenvs/testing/lib/python3.5/site-packages/icon_font_to_png/command_line.py", line 157, in run
    color=args.color, scale=args.scale)
      File "/home/jonas/.virtualenvs/testing/lib/python3.5/site-packages/icon_font_to_png/icon_font.py", line 175, in export_icon
    out_image.save(os.path.join(export_dir, filename))
      File "/home/jonas/.virtualenvs/testing/lib/python3.5/site-packages/PIL/Image.py", line 1713, in save
    format = EXTENSION[ext]
    KeyError: ''
`

**Comment by pawelad** [comment]
@MrGreenTea I believe I fixed the issue, but could you test it locally? To do that, you'll need to install the latest master branch:
```
$ pip install git+https://github.com/Pythonity/icon-font-to-png.git -U
$ icon-font-to-png --css Keyrune-master/css/keyrune.css --ttf Keyrune-master/fonts/keyrune.ttf --size 64 ALL
```

The bug is because of the CSS structure of the icon font, which also is responsible for rendering the names with the dash (`-`) in front of the actual name. I thought about it a bit but didn't came up with a nice enough solution.
To bypass that, for now you can (temporarily) remove `.ss:before` selector from the CSS file.

Let me know if it works, I will then release a new version to PyPI.

**Comment by MrGreenTea** [comment]
Yeah, the thing with the names was weird too, but it works with a -- after all other parameters.

It works now, thanks for the quick fix

**Comment by pawelad** [comment]
The `.ss:before` is also treated as an icon, and the common prefix between `.ss:before` and `.ss-foo:before` is indeed `ss`, and not `ss-`.

Cool, I'm glad its working : )

**Comment by pawelad** [comment]
Release [v0.4.1](https://github.com/Pythonity/icon-font-to-png/releases/tag/v0.4.1) is live : -)
